import { Minutogram } from './minutogram.model';

export const SAMPLE_MINUTOGRAM: Minutogram = {
  id: 'sample-001',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  deploymentInfo: {
    id: 'info-001',
    project: 'Onboarding Ikigii & Onb Web',
    sprint: 'Sprint 20',
    version: 'Onb Ikigii v3.0.0 · Onb Web v3.1.0',
    responsible: 'Nestor Martínez - Frontend',
    date: '2026-03-22',
    description:
      'Pase a producción de 7 HU del Sprint 20. ' +
      'Incluye integración ONFIDO, búsqueda automática de info personal, validación celular por país, ' +
      'efecto blur y homologación de textos.',
  },
  prerequisites: [
    {
      id: 'pre-001', order: 1,
      category: 'Código / Git',
      activity: 'Todos los tickets del Sprint 20 integrados en la rama QA',
      responsible: 'Nestor Martínez', status: 'Completado',
      observations: 'ABC-13820, ABC-11596, ABC-14872, ABC-14962, ABC-15714, ABC-8448, ABC-11824',
    },
    {
      id: 'pre-002', order: 2,
      category: 'Gateway',
      activity: 'Versión del API Gateway a desplegar definida y documentada',
      responsible: '[Resp. API GW]', status: 'Pendiente',
      observations: 'Pendiente de confirmación por parte del equipo de backend',
    },
    {
      id: 'pre-003', order: 3,
      category: 'Comunicación',
      activity: 'Disponibilidad confirmada: Nestor Martínez, Resp. API GW y Laura Renda (Banco)',
      responsible: 'PM / Tech Lead', status: 'En progreso',
      observations: 'Coordinar ventana de mantenimiento 1:00 am – 4:00 am',
    },
  ],
  phases: [
    { id: 'phase-1',  name: 'FASE 1 — DESPLIEGUE API GATEWAY',            color: '#065f46', order: 1 },
    { id: 'phase-2a', name: 'FASE 2A — DESPLIEGUE FRONTEND · ONB IKIGII', color: '#004066', order: 2 },
    { id: 'phase-2b', name: 'FASE 2B — DESPLIEGUE FRONTEND · ONB WEB',    color: '#004066', order: 3 },
    { id: 'phase-3',  name: 'FASE 3 — VALIDACIÓN Y CIERRE OFICIAL',       color: '#5b21b6', order: 4 },
  ],
  steps: [
    {
      id: 'step-001', order: 1, phaseId: 'phase-1',
      activity: 'Inicio de despliegue API Gateway',
      component: 'API Gateway', responsible: '[Resp. API GW]',
      startTime: '01:00', endTime: '01:50', duration: 50,
      ticketId: '—',
      observations: 'Completar con versión específica, pipeline y procedimiento del API GW.',
    },
    {
      id: 'step-002', order: 2, phaseId: 'phase-1',
      activity: 'Verificación de endpoints API Gateway en Producción',
      component: 'API Gateway', responsible: '[Backend + QA]',
      startTime: '01:50', endTime: '02:00', duration: 10,
      ticketId: '—',
      observations: 'Confirmar que todos los endpoints críticos responden correctamente.',
    },
    {
      id: 'step-003', order: 3, phaseId: 'phase-1',
      activity: '⚡ GO / NO-GO — API Gateway',
      component: 'API Gateway', responsible: '[Tech Lead]',
      startTime: '02:00', endTime: '02:05', duration: 5,
      ticketId: '—',
      observations: 'GO: Continuar con el despliegue del Frontend. NO-GO: Ejecutar rollback del API Gateway.',
    },
    {
      id: 'step-004', order: 4, phaseId: 'phase-2a',
      activity: 'Inicio de despliegue Frontend Onb Ikigii v3.0.0',
      component: 'Onboarding Ikigii', responsible: 'Nestor Martínez',
      startTime: '02:05', endTime: '02:15', duration: 10,
      ticketId: 'ABC-13820, ABC-11596, ABC-14872, ABC-14962, ABC-15714, ABC-8448, ABC-11824',
      observations: 'Deploy de v3.0.0 en Producción. Verificar que el pipeline CI/CD complete exitosamente.',
    },
    {
      id: 'step-005', order: 5, phaseId: 'phase-2a',
      activity: 'Verificación de despliegue exitoso — Onb Ikigii',
      component: 'Onboarding Ikigii', responsible: 'Nestor Martínez',
      startTime: '02:15', endTime: '02:20', duration: 5,
      ticketId: '—',
      observations: 'Confirmar versión 3.0.0 activa en Producción. Verificar carga inicial en navegador.',
    },
    {
      id: 'step-006', order: 6, phaseId: 'phase-2a',
      activity: '⚡ GO / NO-GO — Onb Ikigii',
      component: 'Onboarding Ikigii', responsible: 'Nestor Martínez',
      startTime: '02:20', endTime: '02:25', duration: 5,
      ticketId: '—',
      observations: 'GO: Continuar con Onb Web. NO-GO: Rollback de Onb Ikigii a v2.0.5.',
    },
    {
      id: 'step-007', order: 7, phaseId: 'phase-2b',
      activity: 'Inicio de despliegue Frontend Onb Web v3.1.0',
      component: 'Onboarding Web', responsible: 'Nestor Martínez',
      startTime: '02:25', endTime: '02:35', duration: 10,
      ticketId: 'ABC-14728, ABC-14675, ABC-15112, ABC-14963, ABC-15714, ABC-8448',
      observations: 'Deploy de v3.1.0 en Producción. Verificar que el pipeline CI/CD complete exitosamente.',
    },
    {
      id: 'step-008', order: 8, phaseId: 'phase-2b',
      activity: 'Verificación de despliegue exitoso — Onb Web',
      component: 'Onboarding Web', responsible: 'Nestor Martínez',
      startTime: '02:35', endTime: '02:40', duration: 5,
      ticketId: '—',
      observations: 'Confirmar versión 3.1.0 activa en Producción. Verificar carga inicial en navegador.',
    },
    {
      id: 'step-009', order: 9, phaseId: 'phase-3',
      activity: 'Pruebas de humo (Smoke Tests) — Onb Ikigii + Onb Web',
      component: 'Todos', responsible: 'Laura Renda (Banco)',
      startTime: '02:40', endTime: '03:05', duration: 25,
      ticketId: 'ABC-13820, ABC-14872, ABC-8448, ABC-14728, ABC-14675, ABC-15112, ABC-14963',
      observations: 'Validación de todos los tickets del release en ambas aplicaciones.',
    },
    {
      id: 'step-010', order: 10, phaseId: 'phase-3',
      activity: '⚡ GO / NO-GO Final — Aprobación Producción',
      component: 'Todos', responsible: 'Laura Renda (Banco)',
      startTime: '03:05', endTime: '03:10', duration: 5,
      ticketId: '—',
      observations: 'GO: Pase exitoso — proceder al cierre oficial. NO-GO: Ejecutar plan de rollback.',
    },
    {
      id: 'step-011', order: 11, phaseId: 'phase-3',
      activity: 'Monitoreo de logs y métricas post-deploy',
      component: 'Infraestructura', responsible: 'Nestor Martínez',
      startTime: '03:10', endTime: '03:25', duration: 15,
      ticketId: '—',
      observations: 'Revisar logs en los primeros 15 min post-despliegue. Error rate < 1% aceptable.',
    },
    {
      id: 'step-012', order: 12, phaseId: 'phase-3',
      activity: 'CIERRE OFICIAL DEL PASE',
      component: 'Todos', responsible: 'Todos los responsables',
      startTime: '03:25', endTime: '03:30', duration: 5,
      ticketId: '—',
      observations: 'Confirmar aprobación de todos. Actualizar registros: Onb Ikigii v3.0.0 y Onb Web v3.1.0 activos.',
    },
  ],
};
